### ISSUE TITLE
It is not work 

### ISSUE THREAD

**Issue by sucof** [sensepost/wadi#6]
Hi,
     When I start waid with "python wadi.py randoms.js 8000", it always like that:
D:\wadi>python wadi.py randoms.js 8000
[_] Running Server Process 3732
Serving at port 8000
Process Process-4:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\wadi\wadi.py", line 28, in run_debugger
    debugger.run_Browser('IE')
  File "D:\wadi\wadi_debug_win.py", line 180, in run_Browser
    self.p1,self.p1name = self.system.find_processes_by_filename(self.exe)[0]
IndexError: list index out of range
[_] Debugger Process 3620 exited
[_] No Crashes
[_] No TestCases
[_] Terminating Debugger Process PID: 2504
[_] Debugger Process 2504 exited
[_] No Crashes
[_] No TestCases
Process Process-6:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\wadi\wadi.py", line 28, in run_debugger
    debugger.run_Browser('IE')
  File "D:\wadi\wadi_debug_win.py", line 187, in run_Browser
    self.broker_process,self.broker_name = self.system.find_processes_by_filename(self.rt_broker)[0]
IndexError: list index out of range
[_] Debugger Process 4248 exited
[_] No Crashes
[_] No TestCases
Attached to process C:\Windows\System32\RuntimeBroker.exe
Attached to process C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
Attached to process C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
Attached to process C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
Attached to process C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
[_] Terminating Debugger Process PID: 6044
[_] Debugger Process 6044 exited
[_] No Crashes
[_] No TestCases
Process Process-8:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\wadi\wadi.py", line 28, in run_debugger
    debugger.run_Browser('IE')
  File "D:\wadi\wadi_debug_win.py", line 187, in run_Browser
    self.broker_process,self.broker_name = self.system.find_processes_by_filename(self.rt_broker)[0]
IndexError: list index out of range
[_] Debugger Process 4240 exited
[_] No Crashes
[_] No TestCases
Traceback (most recent call last):
  File "wadi.py", line 125, in <module>
    w.run()
  File "wadi.py", line 98, in run
    if not self.debugger_process.is_alive():
  File "C:\Python27\lib\multiprocessing\process.py", line 159, in is_alive
    return self._popen.returncode is None
KeyboardInterrupt
Process Process-9:
........
and my edge version is 25.10586.0.0, and OS is win10  professional  with 32bit.
Thanks!

**Comment by ssherei** [comment]
Heya,

The error indicates that Wadi was not able to find the RunTimeBroker.exe process, can I ask whats your setup. 

Regards, 
Saif

**Comment by sucof** [comment]
Hi,
I just setup pip install winappdbg, distorm3-3.win32.exe, PyV8-1.0-preview-r443.win32-py2.7.exe and pip install twisted. Then I encountered such a problem when I want to Fuzzing.

Regards,
sucof

**Comment by ssherei** [comment]
Hey,

I was asking about your windows version and HW specs ??

Thanks,
Saif

**Comment by sucof** [comment]
yeh, 
sorry for my stupid, my test environment is a VM(12.0.0 build-2985596), VM's OS is win10 professional with 32bit,Th2(10.0.10586),  and specific parameter of HW specs are: CPU is I5(750), RAM is 2G. Is it?

Thanks,
sucof

**Comment by ssherei** [comment]
you can comment out the line 187 in wadi_debug_win.py
